### ISSUE TITLE
promise_counts table not getting populated

### ISSUE THREAD

**Issue by MadhuChittam** [evolvethinking/delta_reporting#38]
We are working on implementing deltareporting.

I have a sample promise that is logging promise outcome.

[root@vlltccfecomm log]# cat promises
BEGIN 2017-05-15T09:11:19-0500
efl_copy_files_single2 ;; 10.7.64.59 ;; /etc/RHNS-CA-CERT

final log entry (one of the line)

2017-05-15T09:16:07-0500 ;; 10_7_64_59_handle_efl_copy_files_single2_kept ;; efl_copy_files_single2 ;; 10.7.64.59 ;; kept ;; /etc/RHNS-CA-CERT

no errors in generating final  log file  and loading to database.
However promise_counts table is not getting populated.

I did download all test cases and ‘perl DeltaR.pl test’ executes without errors and all tables are populated .

Anything I am missing ? there was no error logged anywhere.  We are using RHEL6.

**Comment by neilhwatson** [comment]
Promise counts are populated by the delta-cron script which you must schedule to run once a day.
