### ISSUE TITLE
Delta report not working on RHEL 7

### ISSUE THREAD

**Issue by chittaranjan2014** [evolvethinking/delta_reporting#39]
We have configured step by step in RHEL 7 as per instructions, but still we are unable to view help page as well. ex: http://<server fqdn>:8080/help. This page also not opening.

It would be better if you can reply quick

**Comment by chittaranjan2014** [comment]
http://:8080/help. i mean http://servername:8080/help

**Comment by chittaranjan2014** [comment]
Please help, we are trying to config rhel 7

**Comment by neilhwatson** [comment]
Please post your DeltaR.conf file.

**Comment by chittaranjan2014** [comment]
# Delta Reporting is a central server compliance log that uses CFEngine.

#

# Copyright (C) 2016 Neil H. Watson http://watson-wilson.ca

#

# This program is free software: you can redistribute it and/or modify

# it under the terms of the GNU General Public License as published by

# the Free Software Foundation, either version 3 of the License, or

# (at your option) any later version.

#

# This program is distributed in the hope that it will be useful,

# but WITHOUT ANY WARRANTY; without even the implied warranty of

# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

# GNU General Public License for more details.

#

# You should have received a copy of the GNU General Public License

# along with this program.  If not, see <http://www.gnu.org/licenses/>.

 

{

   db_name         => "delta_reporting",

   db_user         => "deltar_ro",

   db_pass         => "deltar",

   db_wuser        => "deltar_rw",

   db_wpass        => "deltar",

   db_host         => "localhost",

 

# Change these, and rotate out old ones.

   secrets         => [ 'secret passphrase', 'old secret passphrase' ],

 

   record_limit    => 1000, # Limit the number of records returned by a query.

   agent_table     => "agent_log",

   promise_counts  => "promise_counts",

   inventory_table => "inventory_table",

   inventory_limit => 20, # mintes to look backwards for inventory query

   client_log_dir  => "/var/cfengine/delta_reporting/log/client_logs",

   delete_age      => 90, # (days) Delete records older than this.

   reduce_age      => 10, # (days) Reduce duplicate records older than this to one per day

 

   hypnotoad       => {

      proxy          => 1,

      #production     => 1,

      listen         => [ 'http://vlltccfecomprod.fisdev.local:8080' ],

   },

};

Also no log file created or nothing is logged to syslog.  Please let us know how to enable/add logging

**Comment by neilhwatson** [comment]
Production flag is off, so you should see logs at the console by hypnotoad. Also, what does `ss -ln |grep 8080` show? Do you see DeltaR is the proc table?

Starting DR with `cd <dir where delta reporting is installed/app; ./bin/morbo` will show debugging.

**Comment by chittaranjan2014** [comment]
root@vlltccfecomprod ~]# ss -ln|grep 8080
tcp    LISTEN     0      128    10.7.80.16:8080                  *:*  

[root@vlltccfecomprod ~]# ps -ef|grep deltar
deltar   24755     1  0 10:14 ?        00:00:00 /opt/delta_reporting/app/DeltaR.pl
deltar   24756 24755  0 10:14 ?        00:00:00 /opt/delta_reporting/app/DeltaR.pl
deltar   24757 24755  0 10:14 ?        00:00:00 /opt/delta_reporting/app/DeltaR.pl
deltar   24758 24755  0 10:14 ?        00:00:00 /opt/delta_reporting/app/DeltaR.pl
deltar   24759 24755  0 10:14 ?        00:00:00 /opt/delta_reporting/app/DeltaR.pl

**Comment by chittaranjan2014** [comment]
it is working fine using morbo. 
With hypnotoad it is just hanging and eventually timing out.

**Comment by neilhwatson** [comment]
If you run `./DeltaR.pl test` it will run through all dev unit tests. It will drop the database during testing, so don't do this on a prod env where you care about the data.

**Comment by chittaranjan2014** [comment]
but how will get delta report as per my issue?

**Comment by neilhwatson** [comment]
There's nothing wrong with anything you've given me, and I've tested this on RHEL7 in the past. So, the tests may turn up something. Another suggesting is to run the commands in the startup script by hand to see what happens.
